baseURL = "https://www.garderielooma.com/"

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

languageCode = "fr-ca"
title = "Looma ~ Garderie en milieu familial à pédagogie par la nature"

[params]
  favicon = "favicon.png"
  description = ""

  [params.meta]
    keywords = "Garderie Sherbrooke, Garderie Rock-Forest, Garderie en milieu familial, Garderie à pédagogie par la nature"
